[package]
name = "locale"
version = "0.2.2-pre"
description = "Library for basic localization."
authors = [
    "Ben S <ogham@bsago.me>",
    "Jan Hudec <bulb@ucw.cz>",
]
license = "MIT"

documentation = "https://docs.rs/locale/"
repository = "https://github.com/rust-locale/rust-locale/"
readme = "README.md"
keywords = ["i18n", "g12n", "l10n"]

[dependencies]
libc = "0.2"
locale_config = ">= 0.2.1"

[package.metadata.release]
upload-doc = true
